version: '3'

networks:
  rabbitnet:
    name: rabbitnet
    driver: HOST

 

services:
  rmq0:
    build: rmq
    hostname: rmq0
    networks:
      rabbitnet:
        aliases:
          - rmq0.local
    environment:
      - LOG=debug
    volumes:
      - ./data/rmq0:/var/lib/rabbitmq/mnesia
      - ./log/rmq0:/var/log/rabbitmq
    command:
      - --uri=amqp://haproxy.local
      - --servers-startup-timeout=45
      - --rate=100
      - --producers=10
      - --consumers=10
      - --confirm=32
      - --confirm-timeout=800
      - --flag=mandatory
      - --flag=persistent
      - --queue-args=x-queue-type=quorum
      - --auto-delete=false
      - --queue-pattern='perf-test-%03d'
      - --queue-pattern-from=0
      - --queue-pattern-to=9
    restart: on-failure


